Vagrant.configure("2") do |config|
  config.vm.box = "opnsense"

  # sepecial configurations for bsd shell / opnsense stuff
  config.ssh.sudo_command = "%c"
  config.ssh.shell = "/bin/sh"
  config.ssh.password = "opnsense"
  config.ssh.username = "root"
  # we do not need the default sync folder at all
  config.vm.synced_folder ".", "/vagrant", disabled: true

end
